[package]
name = "flare-client"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Async Rust HTTP client for Flare"
readme = "README.md"

[dependencies]
flare-types = { path = "../../crates/flare-types", version = "0.1.0" }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
